whitelist = ["127.0.0.1/8", "10.0.0.0/8"]
maxincidents= 5
incidenttime = "30s"
etcdAddresses = ["http://localhost:2379"]
[Files.bar]
filename = "bar"
regexes = ["Accepted publickey for .+ from (?P<ip>.+) port .*"]
